### ISSUE TITLE
Failed to run wtih my local environment

### ISSUE THREAD

**Issue by youtsumi** [monodera/covid19plot#1]
Failed to run as the following error happened. Any thought?
``` bash
python ./make_covid19_plots.py
Traceback (most recent call last):
  File "./make_covid19_plots.py", line 468, in <module>
    plot_covid19_timeseries(outdir, df_places_to_plot)
  File "./make_covid19_plots.py", line 343, in plot_covid19_timeseries
    df_global = read_jhu_data()
  File "./make_covid19_plots.py", line 30, in read_jhu_data
    id_list = df_confirmed.columns.to_list()[:4]
AttributeError: 'Index' object has no attribute 'to_list'
```

I intended to include New York state data.

**Comment by monodera** [comment]
Which version of Pandas are you using? I'm running the script with 1.0.3 with Python 3.6.10.

**Comment by youtsumi** [comment]
My version was ancient.... '0.23.4'. Also bokeh was 1.0.2 which caused a similar issue. Thank you very much.
